# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0002_auto_20171024_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_list', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friendList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='login_app.User')),
            ],
        ),
    ]
