# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20171024_2230'),
        ('friend_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='friendList',
        ),
        migrations.AddField(
            model_name='list',
            name='friendList',
            field=models.ManyToManyField(related_name='friends', to='login_app.User'),
        ),
    ]
