# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_app', '0002_auto_20171025_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='friend_list',
            new_name='friend',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='friendList',
            new_name='friends',
        ),
    ]
