# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_app', '0003_auto_20171025_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='friends',
            new_name='userfriend',
        ),
    ]
